CPPFLAGS+=-Wall -Wextra -Wpedantic

CFLAGS+=-std=c11

# target: dependecies...
# 	rules/
# 	commands

driver.o: driver.c
	# compile (cc) up to the point of object files (-c)
	# naming the output (-o) driver.o
	# using the input driver.c
	cc -c -o driver.o driver.c
